<?php

/**
 * Implements hook_node_insert().
 */
function example_node_insert($node) {

  if ($node->type != 'article') {
    return;
  }

  dpm($node);
}

/**
 * Implements hook_node_view().
 */
function example_node_view($node, $view_mode, $langcode) {
  if ($node->type != 'article') {
    return;
  }

  if ($view_mode != 'full') {
    return;
  }

  drupal_add_js(drupal_get_path('module', 'example') . '/js/example.js');
}
